- name: Workstation config
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Detect which OS is being used
      ansible.builtin.import_tasks: pre_tasks/detect_os.yml
    - name: Import some secrets
      ansible.builtin.import_tasks: pre_tasks/import_secrets.yml
    - name: Set the host user as a variable
      ansible.builtin.import_tasks: pre_tasks/detect_user.yml
